# Generated by Django 4.1.7 on 2024-02-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=512, null=True)),
                ('Dob', models.DateField(blank=True, null=True)),
                ('Sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('Mobile_nos', models.CharField(blank=True, default='+91', max_length=13, null=True)),
                ('Alt_Mobile_nos', models.CharField(blank=True, default='+91', max_length=13, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Guardian', models.CharField(blank=True, max_length=512, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Marital_Status', models.CharField(blank=True, choices=[('Unmarried', 'Unmarried'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=100, null=True)),
                ('Profession', models.CharField(blank=True, max_length=100, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
