# Generated by Django 4.1.7 on 2024-02-08 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entry_No', models.IntegerField(blank=True, null=True)),
                ('Profession', models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Reports', 'Reports'), ('Lab', 'Lab'), ('Pharamacy', 'Pharamacy'), ('Undefined', 'Undefined')], max_length=20, null=True)),
                ('DOJ', models.DateField(blank=True, null=True)),
                ('First_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Middle_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7, null=True)),
                ('Blood_Group', models.CharField(blank=True, max_length=10, null=True)),
                ('DOB', models.DateField(max_length=100, null=True)),
                ('Religion', models.CharField(blank=True, max_length=10, null=True)),
                ('Nationality', models.CharField(blank=True, max_length=20, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Details', models.CharField(blank=True, max_length=100, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('AltMobile', models.IntegerField(blank=True, null=True)),
                ('Marital_Status', models.CharField(max_length=100, null=True)),
                ('Education_Details', models.CharField(blank=True, max_length=100)),
                ('Experience_Details', models.CharField(blank=True, max_length=100)),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dept')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
