# Generated by Django 4.1.7 on 2024-02-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Paitent',
            new_name='Patient',
        ),
    ]
