# Generated by Django 4.1.7 on 2024-02-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pharmacyitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyitem',
            name='category',
            field=models.CharField(blank=True, default='Medicine', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyitem',
            name='curr_stock',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
