# Generated by Django 4.1.7 on 2024-02-29 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_pharmacyitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcount', models.IntegerField(blank=True, null=True)),
                ('net_total', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyItemQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pharmacybill')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pharmacyitem')),
            ],
        ),
        migrations.AddField(
            model_name='pharmacybill',
            name='items',
            field=models.ManyToManyField(related_name='items', through='main.PharmacyItemQuantity', to='main.pharmacyitem'),
        ),
        migrations.AddField(
            model_name='pharmacybill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
    ]
