# Generated by Django 4.1.7 on 2024-04-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='date',
            new_name='time',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
